spring.application.name=demo
spring.web.resources.add-mappings=true

# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS (SUPABASE POOLER)
# ==========================================
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.zmjxmdnrglhksrzohzqe
spring.datasource.password=CheckMateGPS@1
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB